[package]
name = "file-clear"
version = "0.1.0"
authors = ["gaofans <1459260220@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.13"
lzma-rs = "0.2.0"